function missionsView(){
  const rows=state.missions.filter(m=>(missionStatus==='ALL'||m.status===missionStatus)&&(`${m.id} ${m.orderNo} ${m.title} ${m.destination}`.toLowerCase().includes(missionQuery.toLowerCase())));
  const selected=state.missions.find(m=>m.id===state.selectedMission)||rows[0];
  return `${pageHead('배송임무 관리','주문을 임무로 전환하고 점검·이륙·복귀·완료 상태를 제어합니다.',`<button class="btn" data-export-csv>${ICONS.download} CSV</button><button class="btn primary" data-new-mission>${ICONS.plus} 신규 임무</button>`)}<section class="split"><article class="card"><div class="toolbar"><div class="filters"><input class="input" id="mission-search" value="${escapeHtml(missionQuery)}" placeholder="임무·주문·배송지 검색"><select class="select" id="mission-status"><option value="ALL">전체 상태</option>${Object.entries(STATUS).map(([k,v])=>`<option value="${k}" ${missionStatus===k?'selected':''}>${v[0]}</option>`).join('')}</select></div><span class="muted" style="font-size:.7rem">총 ${rows.length}건</span></div><div class="table-wrap"><table class="table"><thead><tr><th>임무</th><th>노선</th><th>기체</th><th>상태</th><th>진행률</th><th>예정</th></tr></thead><tbody>${rows.map(m=>`<tr data-select-mission="${m.id}" class="${selected&&selected.id===m.id?'selected':''}"><td><strong>${escapeHtml(m.title)}</strong><small>${m.id} · ${priorityLabel(m.priority)}</small></td><td><strong>${escapeHtml(m.origin)}</strong><small>→ ${escapeHtml(m.destination)}</small></td><td>${m.droneId||'-'}<small>${m.pilot||'미배정'}</small></td><td>${statusBadge(m.status)}</td><td><strong>${m.progress}%</strong><div class="progress" style="width:80px;margin-top:6px"><span style="width:${m.progress}%"></span></div></td><td>${m.etaMin?`${m.etaMin}분`:'-'}</td></tr>`).join('')}</tbody></table></div></article>${missionDetail(selected)}</section>`;
}
function missionDetail(m){ if(!m)return '<article class="card detail-panel"><div class="empty"><div class="empty-icon">↗</div>임무를 선택해 주세요.</div></article>';
  const allDone=Object.values(m.checks).every(Boolean); const d=state.drones.find(x=>x.id===m.droneId); const b=state.batteries.find(x=>x.id===m.batteryId);
  return `<article class="card detail-panel"><div class="detail-hero"><div class="detail-hero-top"><span class="mono">${m.id}</span>${statusBadge(m.status)}</div><h3>${escapeHtml(m.title)}</h3><p>${escapeHtml(m.origin)} → ${escapeHtml(m.destination)}</p></div><div class="detail-grid"><div class="detail-item"><span>기체 / 조종자</span><strong>${m.droneId||'미배정'} · ${m.pilot||'-'}</strong></div><div class="detail-item"><span>배터리</span><strong>${m.batteryId||'-'} · ${b?b.soc:'-'}%</strong></div><div class="detail-item"><span>화물</span><strong>${escapeHtml(m.cargo)} · ${m.payloadKg}kg</strong></div><div class="detail-item"><span>수령인</span><strong>${escapeHtml(m.recipient)}</strong></div><div class="detail-item"><span>진행률</span><strong>${m.progress}% · ETA ${m.etaMin}분</strong></div><div class="detail-item"><span>통신 / GNSS</span><strong>${d?`${d.link}% · ${d.satellites}위성`:'-'}</strong></div></div><div class="card-head" style="border-top:1px solid var(--slate-100)"><div><h3>비행 전 안전점검</h3><p>${allDone?'전체 점검 완료':'모든 항목 완료 후 이륙 가능'}</p></div><button class="btn small" data-check-all="${m.id}">전체 점검</button></div><div class="checklist">${Object.entries(CHECK_LABELS).map(([k,l])=>`<button class="check-row ${m.checks[k]?'done':''}" data-toggle-check="${m.id}" data-check-key="${k}"><span class="check-box">${m.checks[k]?'✓':''}</span><span>${l}</span></button>`).join('')}</div><div class="detail-actions">${missionButtons(m,allDone)}</div></article>`;
}
function missionButtons(m,allDone){
  if(m.status==='READY')return `<button class="btn primary" data-mission-action="START" data-mission-id="${m.id}" ${!allDone||!m.droneId||!m.batteryId?'disabled':''}>이륙 승인·시작</button><button class="btn" data-auto-assign="${m.id}">자동 배정</button>`;
  if(m.status==='APPROVED')return `<button class="btn green" data-mission-action="START" data-mission-id="${m.id}">임무 시작</button>`;
  if(m.status==='IN_FLIGHT')return `<button class="btn warning" data-mission-action="HOLD" data-mission-id="${m.id}">일시대기</button><button class="btn danger" data-mission-action="RTH" data-mission-id="${m.id}">즉시복귀</button><button class="btn green" data-mission-action="COMPLETE" data-mission-id="${m.id}">배송완료</button>`;
  if(m.status==='HOLDING')return `<button class="btn primary" data-mission-action="RESUME" data-mission-id="${m.id}">운항재개</button><button class="btn danger" data-mission-action="RTH" data-mission-id="${m.id}">즉시복귀</button>`;
  if(m.status==='RETURNING')return `<button class="btn green" data-mission-action="COMPLETE" data-mission-id="${m.id}">착륙·종료</button>`;
  if(m.status==='COMPLETED')return `<button class="btn" data-view="proofs">배송증빙 보기</button>`;
  return '';
}

function fleetView(){ return `${pageHead('드론 관리','기체별 비행·통신·정비 상태를 관리합니다.')}<section class="grid entity-grid">${state.drones.map(d=>`<article class="entity"><div class="entity-top"><div><h3>${d.name}</h3><p>${d.id} · ${d.model}</p></div>${statusBadge(d.status==='IN_FLIGHT'?'IN_FLIGHT':d.status==='READY'?'READY':d.status==='MAINTENANCE'?'CANCELLED':'READY')}</div><div class="metric-row"><div class="metric"><span>배터리</span><strong>${d.battery}%</strong></div><div class="metric"><span>통신</span><strong>${d.link}%</strong></div><div class="metric"><span>위성</span><strong>${d.satellites}</strong></div><div class="metric"><span>고도</span><strong>${d.altitude}m</strong></div><div class="metric"><span>속도</span><strong>${d.speed}km/h</strong></div><div class="metric"><span>누적비행</span><strong>${d.flightHours}h</strong></div></div><div class="bar ${d.battery<30?'danger':d.battery<55?'warning':''}"><span style="width:${d.battery}%"></span></div><div class="actions" style="margin-top:13px"><button class="btn small" data-select-drone="${d.id}">기체상세</button>${['IN_FLIGHT','HOLDING'].includes(d.status)?`<button class="btn small danger" data-drone-rth="${d.id}">복귀명령</button>`:''}</div></article>`).join('')}</section>`; }
function batteryView(){ return `${pageHead('스마트배터리','SOC·SOH·온도·셀 편차를 기준으로 임무 투입 가능성을 판단합니다.')}<section class="grid entity-grid">${state.batteries.map(b=>{const st=batteryStatus(b.status);return `<article class="entity"><div class="entity-top"><div><h3>${b.id}</h3><p>${b.droneId?`${b.droneId} 장착`:'보관 랙'}</p></div><span class="status ${st[1]}">${st[0]}</span></div><div class="metric-row"><div class="metric"><span>SOC</span><strong>${b.soc}%</strong></div><div class="metric"><span>SOH</span><strong>${b.soh}%</strong></div><div class="metric"><span>온도</span><strong>${b.temp}℃</strong></div><div class="metric"><span>사이클</span><strong>${b.cycles}</strong></div><div class="metric"><span>셀 편차</span><strong>${b.cellDiff}V</strong></div><div class="metric"><span>예상비행</span><strong>${Math.max(0,Math.round(b.soc*.29))}분</strong></div></div><div class="bar ${b.soh<85||b.cellDiff>.05?'danger':b.soc<55?'warning':''}"><span style="width:${b.soc}%"></span></div>${b.status!=='IN_USE'?`<div class="actions" style="margin-top:13px"><button class="btn small ${b.status==='QUARANTINE'?'primary':'danger'}" data-toggle-battery="${b.id}">${b.status==='QUARANTINE'?'격리 해제':'정비 격리'}</button></div>`:''}</article>`}).join('')}</section>`; }
function safetyView(){ const list=state.alerts.slice().sort((a,b)=>Number(a.ack)-Number(b.ack)||new Date(b.createdAt)-new Date(a.createdAt)); return `${pageHead('안전경보 센터','기체·배터리·항로·통신 이상을 확인하고 조치 이력을 남깁니다.',`<button class="btn" data-ack-all>전체 확인</button><button class="btn warning" data-create-alert>시험경보 생성</button>`)}<article class="card"><div class="card-body alert-list">${list.map(alertRow).join('')}</div></article>`; }
function proofsView(){ return `${pageHead('배송 완료 증빙','완료 좌표, 수령 OTP, 온도기록과 인수증을 확인합니다.',`<button class="btn" data-export-proof>${ICONS.download} 증빙 CSV</button>`)}<article class="card"><div class="table-wrap"><table class="table"><thead><tr><th>증빙번호</th><th>임무/주문</th><th>수령인</th><th>완료시간</th><th>OTP</th><th>좌표</th><th>온도</th></tr></thead><tbody>${state.proofs.map(p=>`<tr data-proof="${p.id}"><td><strong>${p.id}</strong></td><td><strong>${p.missionId}</strong><small>${p.orderNo}</small></td><td>${escapeHtml(p.recipient)}</td><td>${fmtDateTime(p.completedAt)}</td><td class="mono">${p.otp}</td><td class="mono">${p.lat.toFixed(5)}, ${p.lng.toFixed(5)}</td><td>${p.tempRange}</td></tr>`).join('')}</tbody></table></div></article>`; }
function reportsView(){ const values=[7,9,8,12,11,13,12]; return `${pageHead('운영리포트','배송성과, 기체가동률, 안전경보 지표를 분석합니다.',`<button class="btn" data-print>인쇄</button><button class="btn primary" data-export-report>${ICONS.download} 리포트 CSV</button>`)}<section class="grid kpi-grid"><article class="kpi"><div class="kpi-label">정시 배송률</div><div class="kpi-value">${Math.round(state.stats.onTime/state.stats.today*100)}%</div><div class="kpi-foot"><span class="trend">목표 90%</span></div></article><article class="kpi"><div class="kpi-label">평균 임무시간</div><div class="kpi-value">18.4분</div><div class="kpi-foot">최근 7일 평균</div></article><article class="kpi"><div class="kpi-label">기체 가동률</div><div class="kpi-value">71%</div><div class="kpi-foot">운항 가능 3 / 4대</div></article><article class="kpi"><div class="kpi-label">경보 조치율</div><div class="kpi-value">${Math.round(state.alerts.filter(a=>a.ack).length/state.alerts.length*100)}%</div><div class="kpi-foot">누적 ${state.alerts.length}건</div></article></section><section class="grid dashboard-grid"><article class="card"><div class="card-head"><div><h2>최근 7일 배송 건수</h2><p>일별 완료 임무</p></div></div><div class="chart">${values.map((v,i)=>`<div class="chart-col"><div class="chart-bar" style="height:${v/13*100}%" title="${v}건"></div><small>${['월','화','수','목','금','토','일'][i]}</small></div>`).join('')}</div></article><article class="card"><div class="card-head"><h2>운영 제안</h2></div><div class="card-body"><div class="alert-list"><div class="alert-row"><i class="alert-severity INFO"></i><div><strong>BAT-006 교체 검토</strong><p>SOH 79%, 셀 편차 0.068V로 계속 격리 권장</p></div></div><div class="alert-row"><i class="alert-severity"></i><div><strong>오후 풍속 모니터링</strong><p>15시 이후 풍속 상승 가능성에 대비한 여유항로 권장</p></div></div><div class="alert-row"><i class="alert-severity INFO"></i><div><strong>DR-001 예방정비</strong><p>예정 정비까지 21시간 남음</p></div></div></div></div></article></section>`; }
function connectionView(){ const s=state.settings; return `${pageHead('기체 연결 설정','MAVLink 또는 제조사 SDK 게이트웨이가 준비되면 HTTPS API로 연결합니다.',`<button class="btn" data-reset>${ICONS.reset} 데모 초기화</button>`)}<section class="grid dashboard-grid"><article class="card"><div class="card-head"><div><h2>운영 모드</h2><p>실기체가 없을 때는 시뮬레이션 모드를 유지하십시오.</p></div></div><div class="card-body"><div class="form-grid"><div class="field full"><label>실행 모드</label><select class="select" id="connection-mode"><option value="simulation" ${s.mode==='simulation'?'selected':''}>시뮬레이션 — 안전한 가상 운항</option><option value="gateway" ${s.mode==='gateway'?'selected':''}>게이트웨이 — 실제 텔레메트리/API</option></select></div><div class="field full"><label>게이트웨이 주소</label><input class="input" id="gateway-url" value="${escapeHtml(s.gatewayUrl)}" placeholder="https://gateway.example.com"><div class="field-help">게이트웨이는 GET /api/health, GET /api/state, POST /api/commands를 지원하고 CORS와 TLS가 설정되어야 합니다.</div></div><div class="field full"><label>기체 API 키</label><input class="input" id="gateway-key" type="password" value="${escapeHtml(s.apiKey)}" placeholder="기체별 발급 키"><div class="field-help">현재 데모는 키를 이 브라우저 저장소에 보관합니다. 상용 환경에서는 서버 비밀관리 기능을 사용해야 합니다.</div></div></div><div class="actions" style="margin-top:16px"><button class="btn primary" data-save-connection>설정 저장</button><button class="btn" data-test-connection>연결 시험</button></div></div></article><div class="stack"><article class="card"><div class="card-head"><h2>연결 상태</h2></div><div class="card-body"><div class="connection-status"><i class="connection-light ${s.gatewayStatus==='online'?'online':s.gatewayStatus==='failed'?'failed':''}"></i><div><strong>${s.mode==='simulation'?'시뮬레이션 활성':s.gatewayStatus==='online'?'게이트웨이 응답 정상':s.gatewayStatus==='failed'?'연결 실패':'연결 대기'}</strong><p class="muted" style="margin:5px 0 0;font-size:.68rem">${s.lastGatewayCheck?`마지막 확인 ${fmtDateTime(s.lastGatewayCheck)}`:'연결 시험 전'}</p></div></div></div></article><article class="card"><div class="card-head"><h2>권장 연결 구조</h2></div><div class="card-body"><div class="codebox">PX4 / ArduPilot FC
  ↓ MAVLink 2
Raspberry Pi / Jetson Gateway
  ↓ HTTPS + VPN
D-LOGIS API Adapter
  ↓ SSE / WebSocket
관제센터 웹앱</div><p class="muted" style="font-size:.68rem;line-height:1.6;margin:12px 0 0">실제 이륙·RTL 명령은 기체별 안전조건, COMMAND_ACK, 비행모드 재확인 로직을 거친 뒤 활성화해야 합니다.</p></div></article></div></section>`; }

function pilotView(){
  const m=state.missions.find(x=>x.pilot==='김도윤'&&['READY','APPROVED','IN_FLIGHT','HOLDING','RETURNING'].includes(x.status))||state.missions.find(x=>['READY','APPROVED','IN_FLIGHT'].includes(x.status));
  if(!m)return mobileShell(pageHead('현장 조종자','배정된 임무가 없습니다.'));
  const d=state.drones.find(x=>x.id===m.droneId),b=state.batteries.find(x=>x.id===m.batteryId),allDone=Object.values(m.checks).every(Boolean);
  return mobileShell(`<div class="page-head"><div><h1>현장 운항</h1><p>${m.pilot||'배정 조종자'} · ${m.id}</p></div><button class="btn icon" data-role-menu>⌄</button></div><section class="mobile-hero"><div>${statusBadge(m.status)}</div><h1>${escapeHtml(m.title)}</h1><p>${escapeHtml(m.origin)} → ${escapeHtml(m.destination)}</p><div class="mobile-stats"><div class="mobile-stat"><span>기체</span><strong>${m.droneId||'-'}</strong></div><div class="mobile-stat"><span>배터리</span><strong>${b?b.soc:'-'}%</strong></div><div class="mobile-stat"><span>ETA</span><strong>${m.etaMin||0}분</strong></div></div></section><article class="card" style="margin-top:14px"><div class="card-head"><div><h2>비행 전 체크리스트</h2><p>${allDone?'이륙 조건 충족':'항목을 순서대로 확인하십시오.'}</p></div><button class="btn small" data-check-all="${m.id}">전체 점검</button></div><div class="card-body checklist" style="padding:14px">${Object.entries(CHECK_LABELS).map(([k,l])=>`<button class="check-row ${m.checks[k]?'done':''}" data-toggle-check="${m.id}" data-check-key="${k}"><span class="check-box">${m.checks[k]?'✓':''}</span><span>${l}</span></button>`).join('')}</div></article><article class="card" style="margin-top:14px"><div class="card-head"><h2>운항 상태</h2><span class="status ${d&&d.link>80?'green':'amber'}">통신 ${d?d.link:0}%</span></div><div class="card-body"><div class="metric-row"><div class="metric"><span>고도</span><strong>${d?d.altitude:0}m</strong></div><div class="metric"><span>속도</span><strong>${d?d.speed:0}km/h</strong></div><div class="metric"><span>GNSS</span><strong>${d?d.satellites:0}</strong></div></div><div class="progress" style="margin-top:15px;height:10px"><span style="width:${m.progress}%"></span></div><p class="muted" style="font-size:.68rem;text-align:center">임무 진행률 ${m.progress}%</p></div></article><div class="bottom-actions">${missionButtons(m,allDone)}</div>`); }
function recipientView(){ const m=state.missions.find(x=>['IN_FLIGHT','HOLDING','RETURNING'].includes(x.status))||state.missions.find(x=>x.status==='COMPLETED'); const p=state.proofs.find(x=>x.missionId===m.id); const otp=p?p.otp:'2749'; const steps=[['주문 접수',true],['기체 배정',true],['드론 출발',m.status!=='READY'],['배송지 접근',m.progress>70||m.status==='COMPLETED'],['수령 완료',m.status==='COMPLETED']]; return mobileShell(`<div class="page-head"><div><h1>배송 조회</h1><p>${m.orderNo}</p></div><button class="btn icon" data-role-menu>⌄</button></div><section class="mobile-hero"><div>${statusBadge(m.status)}</div><h1>${m.status==='COMPLETED'?'배송이 완료되었습니다':`약 ${m.etaMin}분 후 도착`}</h1><p>${escapeHtml(m.cargo)} · ${m.droneId}</p><div class="mobile-stats"><div class="mobile-stat"><span>진행률</span><strong>${m.progress}%</strong></div><div class="mobile-stat"><span>기체</span><strong>${m.droneId}</strong></div><div class="mobile-stat"><span>고도</span><strong>${state.drones.find(d=>d.id===m.droneId)?.altitude||0}m</strong></div></div></section><article class="card" style="margin-top:14px"><div class="card-head"><div><h2>수령 OTP</h2><p>배송기사 또는 화물함에 입력</p></div><button class="btn small" data-copy-otp="${otp}">${ICONS.copy} 복사</button></div><div class="card-body"><div class="otp">${otp.split('').map(x=>`<span>${x}</span>`).join('')}</div><p class="muted" style="text-align:center;font-size:.68rem">수령 전까지 OTP를 타인에게 공유하지 마십시오.</p></div></article><article class="card" style="margin-top:14px"><div class="card-head"><h2>배송 진행</h2></div><div class="card-body timeline">${steps.map((s,i)=>`<div class="timeline-row ${s[1]?'done':(!steps[i-1]||steps[i-1][1])?'active':''}"><div class="timeline-dot">${s[1]?'✓':i+1}</div><div><strong>${s[0]}</strong><small>${s[1]?'처리 완료':'진행 예정'}</small></div></div>`).join('')}</div></article>${m.status==='COMPLETED'?`<button class="btn green" style="width:100%;margin-top:14px;min-height:48px" data-role="admin">배송증빙 확인</button>`:'<button class="btn" style="width:100%;margin-top:14px;min-height:48px" data-support>배송 문의</button>'}`); }
function mobileShell(content){ return `<div class="shell">${topbar()}<main class="mobile-role">${content}</main></div>`; }
